### PR TITLE
Implements shadow jar and backfills README

### PR DESCRIPTION
**Pull request by adriancole**
This corrects shadow configuration and backfills documentation on how to
use it.

The shadow jar was not configured correctly, mostly due to the "spark"
scope, which was not necessary to call out. This removes that scope and
defers to "compile". The impact is that if a user expects to exclude
spark, or handle it differently, they should just exclude the transitive
dep.

This also renames the env variable `ZIPKIN_KEYSPACE` to
`CASSANDRA_KEYSPACE`. This properly aligns the namespace to upstream and
other cassandra-specific properties.

### CODE REVIEW

**Comment by adriancole** [comment]
incidentally, I fixed this to help @prat0318, who was formerly using gradle to run the job in production. When errors occurrred, they were obfuscated by gradle console layering. By supporting a fat jar, we are closer to publishing a release and also make mean-time usage far more straight-forward.

**Comment by adriancole** [comment]
nothing notable on build failures, and doesn't fail locally. kicking

**Comment by yurishkuro** [comment]
lgtm

**Comment by adriancole** [comment]
build fixed via https://github.com/openzipkin/zipkin-dependencies-spark/pull/12

**Pull request merged**
